language: node_js
node_js:
  - 4
  - 6

install:
  - npm install -g mocha istanbul coveralls mocha-lcov-reporter
  - npm install

script:
  - npm test

after_script:
  - npm run-script coverage
  - npm run-script coveralls

notifications:
  email: EMAIL
